[project]
name = "taier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "LukaPerkovic", email = "luka.m.perkovic@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
taier = "taier:main"

[build-system]
requires = ["uv_build>=0.9.29,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=1.19.1",
    "pre-commit>=4.5.1",
    "ruff>=0.15.0",
]
